'use strict';
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const catalog = [
 {id:'margherita',name:'Margherita',price:12,category:'veg',tag:['LA CLÁSICA','THE CLASSIC','A CLÁSSICA'],description:['Tomate, mozzarella y albahaca fresca. La sencillez nunca supo tan bien.','Tomato, mozzarella and fresh basil. Simple never tasted so good.','Tomate, mozzarella e manjericão fresco. Simples e deliciosa.']},
 {id:'pepperoni',name:'Pepperoni',price:15,category:'meat',tag:['LA FAVORITA','THE FAVORITE','A FAVORITA'],description:['Pepperoni crujiente, mozzarella y nuestra salsa de tomate. Un clásico irresistible.','Crispy pepperoni, mozzarella and our tomato sauce. An irresistible classic.','Pepperoni crocante, mozzarella e nosso molho de tomate. Irresistível.']},
 {id:'formaggi',name:'Quattro Formaggi',price:16,category:'veg',tag:['PARA LOS QUESEROS','CHEESE LOVERS','PARA QUEM AMA QUEIJO'],description:['Mozzarella, gorgonzola, parmesano y fontina. Cuatro razones para volver.','Mozzarella, gorgonzola, parmesan and fontina. Four reasons to return.','Mozzarella, gorgonzola, parmesão e fontina. Quatro razões para voltar.']}
];
let lang='es',filter='all',selected=null,cart=[];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const idx=()=>['es','en','pt'].indexOf(lang);
const tr=(es,en,pt)=>[es,en,pt][idx()];
// Only non-personal preferences are persisted. Form data stays in memory.
const pref={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
$$('[data-en]').forEach(el=>{el.dataset.es=el.hasAttribute('data-html')?el.innerHTML:el.textContent});
function language(value){lang=['es','en','pt'].includes(value)?value:'es';document.documentElement.lang=lang;$('#language').value=lang;$$('[data-en]').forEach(el=>{if(el.hasAttribute('data-html'))el.innerHTML=el.dataset[lang];else el.textContent=el.dataset[lang]});pref.set('pv-lang',lang);renderMenu();renderCart()}
function renderMenu(){$('#pizza-grid').innerHTML=catalog.filter(p=>filter==='all'||p.category===filter).map(p=>`<article class="pizza-card"><div class="pizza-image"><img src="assets/${p.id}.webp" alt="Pizza ${p.name}" width="1024" height="1024" loading="lazy"><span class="pizza-tag">${p.tag[idx()]}</span></div><div class="pizza-body"><h3>${p.name}</h3><p>${p.description[idx()]}</p><div class="pizza-bottom"><strong><small>${tr('Desde','From','A partir de')} </small>${money(p.price)}</strong><button data-pizza="${p.id}" aria-label="${tr('Personalizar','Customize','Personalizar')} ${p.name}">+</button></div></div></article>`).join('')}
function openDialog(dialog){dialog.showModal();document.body.style.overflow='hidden'}
$$('dialog').forEach(d=>{d.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.style.overflow=''});$('[data-close]',d).addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
$('#language').addEventListener('change',e=>language(e.target.value));
$('#theme').addEventListener('click',()=>{const theme=document.documentElement.dataset.bsTheme==='dark'?'light':'dark';document.documentElement.dataset.bsTheme=theme;pref.set('pv-theme',theme)});
document.documentElement.dataset.bsTheme=pref.get('pv-theme')==='dark'?'dark':'light';
$('.menu-toggle').addEventListener('click',e=>{const open=$('#nav-links').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});
$$('#nav-links a').forEach(a=>a.addEventListener('click',()=>{$('#nav-links').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderMenu()}));
$('#pizza-grid').addEventListener('click',e=>{const b=e.target.closest('[data-pizza]');if(!b)return;selected=catalog.find(p=>p.id===b.dataset.pizza);$('#pizza-title').textContent=selected.name;$('#pizza-description').textContent=selected.description[idx()];$('#detail-image').src=`assets/${selected.id}.webp`;$('#detail-image').alt=selected.name;$('#pizza-form').reset();updatePrice();openDialog($('#pizza-dialog'))});
function currentPrice(){return selected.price+Number($('#pizza-form [name=size]').value)+($('#pizza-form [name=extra]').checked?2:0)}
function updatePrice(){$('#item-price').textContent=money(currentPrice())}
$('#pizza-form').addEventListener('change',updatePrice);
let toastTimer;function toast(text){$('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#toast').textContent=''},3000)}
$('#pizza-form').addEventListener('submit',e=>{e.preventDefault();const size=Number($('#pizza-form [name=size]').value),extra=$('#pizza-form [name=extra]').checked,key=`${selected.id}-${size}-${extra}`;const row=cart.find(r=>r.key===key);if(row)row.qty++;else cart.push({key,id:selected.id,size,extra,price:currentPrice(),qty:1});$('#pizza-dialog').close();renderCart();toast(tr('Añadida a tu pedido. ¡Buon appetito!','Added to your order. Buon appetito!','Adicionada ao pedido. Buon appetito!'))});
function renderCart(){$$('.cart-count').forEach(c=>c.textContent=cart.reduce((n,r)=>n+r.qty,0));$('#cart-title').textContent=tr('Tu pedido','Your order','Seu pedido');$('#cart-items').innerHTML=cart.length?cart.map(r=>`<div class="cart-row"><div><strong>${catalog.find(p=>p.id===r.id).name}</strong><p>${r.size?'35 cm':'28 cm'}${r.extra?' · + queso':''} · ${money(r.price)}</p><div class="quantity"><button data-qty="-1" data-key="${r.key}" aria-label="Quitar una ${r.id}">−</button><span>${r.qty}</span><button data-qty="1" data-key="${r.key}" aria-label="Añadir una ${r.id}">+</button></div></div><strong>${money(r.qty*r.price)}</strong></div>`).join(''):`<p>${tr('Tu pedido está vacío. Elige tu favorita en la carta.','Your order is empty. Pick a favorite from the menu.','Seu pedido está vazio. Escolha sua favorita no menu.')}</p>`;$('#cart-total').textContent=money(cart.reduce((n,r)=>n+r.qty*r.price,0));$('#checkout').disabled=!cart.length;$('#cart-status').textContent=''}
$$('[data-cart]').forEach(b=>b.addEventListener('click',()=>{renderCart();openDialog($('#cart-dialog'))}));
$('#cart-items').addEventListener('click',e=>{const b=e.target.closest('[data-qty]');if(!b)return;const row=cart.find(r=>r.key===b.dataset.key);row.qty+=Number(b.dataset.qty);cart=cart.filter(r=>r.qty>0);renderCart()});
function whatsapp(){const raw=window.PIZZA_CONFIG?.whatsapp||'';return /^\d{8,15}$/.test(raw)?raw:null}
function request(text,link){$('#request-text').value=text;$('#copy-status').textContent='';$('#send-request').hidden=!link;if(link)$('#send-request').href=link;else $('#send-request').removeAttribute('href');$('#request-note').textContent=link?tr('Revisa el resumen. Continuar abrirá tu aplicación para que tú lo envíes.','Review the summary. Continue opens your app so you can send it.','Revise o resumo. Continue abre seu aplicativo para você enviar.'):tr('Modo demo: aún no hay un contacto configurado. Puedes copiar el resumen; no se ha enviado ningún dato.','Demo mode: no contact configured yet. Copy the summary; no data has been sent.','Modo demo: contato não configurado. Copie o resumo; nenhum dado foi enviado.');openDialog($('#request-dialog'))}
$('#checkout').addEventListener('click',()=>{if(!cart.length)return;const text=['Hola Pizza Viva, quisiera consultar este pedido:',...cart.map(r=>`${r.qty} × ${catalog.find(p=>p.id===r.id).name} (${r.size?'35':'28'} cm${r.extra?', extra queso':''}) — ${money(r.qty*r.price)}`),`Total estimado: ${$('#cart-total').textContent} USD`,$('#fulfillment').value,'Por favor confirmar disponibilidad, entrega y total final.'].join('\n');$('#cart-dialog').close();request(text,whatsapp()?`https://wa.me/${whatsapp()}?text=${encodeURIComponent(text)}`:null)});
$('#lead-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get('name')).trim();if(!name){$('#lead-status').textContent='Escribe tu nombre para continuar.';return}const text=`Hola, me interesa Pizza Viva.\nNombre: ${name}\nCorreo: ${String(data.get('email')).trim()}\nInterés: ${data.get('interest')}\nAcepto que me contacten para responder esta solicitud.`;const email=window.PIZZA_CONFIG?.contactEmail||'';let link=null;if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))link=`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent('Solicitud de personalización · Pizza Viva')}&body=${encodeURIComponent(text)}`;else if(whatsapp())link=`https://wa.me/${whatsapp()}?text=${encodeURIComponent(text)}`;request(text,link)});
$('#copy-request').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#request-text').value);$('#copy-status').textContent=tr('Resumen copiado.','Summary copied.','Resumo copiado.')}catch{$('#request-text').focus();$('#request-text').select();$('#copy-status').textContent=tr('Selecciona y copia el texto manualmente.','Select and copy the text manually.','Selecione e copie o texto manualmente.')}});
if (whatsapp() || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(window.PIZZA_CONFIG?.contactEmail || '')) {
 const notice=$('#contact-notice');
 notice.dataset.es='Revisarás el resumen antes de enviarlo desde tu aplicación. No guardamos tus datos en este sitio.';
 notice.dataset.en='Review your summary before sending from your app. This site does not store your details.';
 notice.dataset.pt='Revise o resumo antes de enviar pelo seu aplicativo. Este site não armazena seus dados.';
}
$('#year').textContent=new Date().getFullYear();language(pref.get('pv-lang')||'es');
